name: pipeline

on: 
  push:
    paths:
      - "./.github/workflows/main.yml"


jobs:

  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: init
        run: terraform init

      - name: plan
        run: terraform plan
